config/routes.rb
Rails.application.routes.draw do
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/' => 'sessions#welcome'
  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  delete 'logout' => "sessions#logout"
  get '/signup' => "users#new"
  post '/signup' => "users#create"
  get '/users/:id', to: 'users#show', as: 'user'
  get '/auth/:provider/callback', to: 'sessions#create'
  resources :reviews, only: [:edit, :destroy, :update, :show]
  resources :books do
    resources :reviews, only:[:new, :create, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :reviews
    has_many :users, through: :reviews
    validates :title, presence: true
    validates :author, presence: true
   

    def self.alpha
        Book.order(title: :asc)
    end


    def status
        if self.completed == true
            'Yes!'
        else
            'No!'
        end
    end
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :book
    belongs_to :user
    validates :content, presence: true
    
  
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :books #Books they have created
    has_many :reviews
    has_many :reviewed_books, through: :reviews, source: :book
    validates :email , presence: true,  uniqueness: true

    def self.find_or_create_by_omniauth(auth_hash)
        self.where(email: auth_hash.info.email).first_or_create do |user|
            user.password = SecureRandom.hex
        end
    end
    def self.find_user(params)
        @user = User.find_by(email: params[:email])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper




end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   
    
    
    def new
        @book = Book.new
    end
    
    def create
        @book = current_user.books.build(book_params)
        if @book.save
            redirect_to user_path(current_user)
        else
            redirect_to :new
        end
    end
   
    def index
        
        @books = Book.alpha
    end

        def show
            @review = Review.new
            @book = Book.find(params[:id])
        end

 
        def destroy
            Book.find(params[:id]).destroy
           redirect_to user_path(current_user)
          end

    private

    def book_params
        params.require(:book).permit(:title, :author, :completed)
    end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
   before_action :require_login
   before_action :require_ownership, only: [:edit, :update]
    
   def new
        @review = Review.new
        @book = Book.find_by(id: params[:book_id])
    end
    
    def create
        @review = Review.new(review_params) 
        @review.book_id = params[:book_id]
        @review.user_id = current_user.id
        if @review.save
            redirect_to review_path(@review)
        else 
            render "new"
        end
    end
    
    def show
        @review = Review.find_by(id: params[:id])
    end

    def index
        @book = Book.find_by(id: params[:book_id])
        @reviews = @book.reviews
    end
    
    def edit
        @review = Review.find_by(id: params[:id])
    end

    def update
        if @review.update(review_params)
            redirect_to review_path(@review)
        else
            render :edit
        end
    end

    private
    def review_params
        params.require(:review).permit(:content)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    helper_method :current_user, :logged_in?
    
    def welcome
    end

    def new
        if current_user
            redirect_to user_path(@current_user)
        else
            @user = User.new
        end
    end

    def create
        if auth_hash = request.env["omniauth.auth"]
            @user = User.find_or_create_by_omniauth(auth_hash)
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        elsif @user.find_user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :login, notice: 'Invalid Username or Password.'
        end
    end  
    
    
    def logout
        logged_in?
        session.destroy
        redirect_to '/'
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end
    
    def show
        current_user
    end
    
    private

    def user_params
        params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
        if session[:user_id]
        @current_user ||= User.find_by(id: session[:user_id])
        end
    end
    
    def logged_in?
        !!current_user
    end

    def require_login
        if !current_user
            redirect_to '/login'
        end
    end

    def require_ownership
        @review = Review.find_by(id: params[:id])
        if @review.user.id != current_user.id
            redirect_to user_path(@current_user)
        end
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<%@books.each do |book|%>
Title: <%= book.title%><br>
Author: <%= book.author%><br>
<%end%>

app/views/books/new.html.erb
<%= render partial: '/shared/errors', locals: {obj: @book}%>

<%= form_for @book do |f|%>
    <%= f.label :title, "Title:" %>
    <%= f.text_field :title%><br>
    <%= f.label :title, "Author:"%>
    <%= f.text_field :author  %><br>
    <%= f.label :completed, "Completed:" %>
    <%= f.check_box :completed%>
    <br>

    <%= f.submit %>
<% end %>

app/views/books/show.html.erb
Title: <%= @book.title%><br>
Author: <%= @book.author%><br>
<%=link_to 'Reviews', book_reviews_path(@book)%><br>
<%= link_to 'Add a Review!', new_book_review_path(@book)%><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProjectFlatiron</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav>
    <%if current_user%>
    Welcome, <%= current_user.email%>!<br>
    <br><%= link_to "Bookshelf", user_path(current_user)%><br>
    <br><%= link_to "Logout", '/logout', method: "delete"%><br><br>
  <%else%>
  Please
<%=link_to "Login", login_path%>
    Or 
    <%= link_to "Signup", signup_path%>!
    </nav>
    <%end%>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
 <h3>Review Form</h3>
 <label>Review content:</label><br>
  <%= f.text_field :content %><br>
  <%= f.submit %>

app/views/reviews/edit.html.erb
<%= form_for [@book, @review], url: "/reviews/#{@review.id}" do |f| %>
<%= render partial: '/shared/errors', locals: {obj: @review}%>
  <%= render partial: 'form', locals:{f: f}%>
<% end %>

app/views/reviews/index.html.erb
<%@book.reviews.each do |review|%>
Book Title:<%=@book.title%>
<br>Reviewer: <%=review.user.email%><br>
<br>Review: <%= review.content %><br>
<br><%= link_to "Edit Review", edit_review_path(review)%><br>
<%end%>

app/views/reviews/new.html.erb
<%= form_for([@book, @review]) do |f|%>
<%= render partial: '/shared/errors', locals: {obj: @review}%>
 <%= render partial: 'form', locals:{f: f}%>
<%end%>

app/views/reviews/show.html.erb
Book Title:<%= @review.book.title%><br>
Your Review:<%= @review.content%><br>
<br><%= link_to "Edit Review", edit_review_path(@review)%><br>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(obj.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<%= render partial: '/shared/errors', locals: {obj: @user}%>
<%= form_with(model: @user, url:'/signup', local: true) do |f|%>
    <%= f.label :email %>
    <%= f.email_field :email %><br><br>
    <%= f.label :password %>
    <%= f.password_field :password %><br><br>
    <%= f.submit "Sign Up"%>
<% end %>

app/views/users/show.html.erb
<nav><%=link_to 'Add a book.', '/books/new'%></nav>
<h1>Bookshelf</h1>
<p><%current_user.books.each do|book|%><br>
    Title:<%=book.title%><br>
    Author:<%=book.author%><br>
    Completed? <%=book.status%><br>
    <%=link_to 'Add a review or Edit a review!', book_path(book)%><br>
     <%= link_to "Delete #{book.title}?", book, method: :delete, data: { confirm: "Are you sure this is a good idea?" } %><br><br>
<%end%>
<br><br><%= link_to "All Books", books_path%><br><br>

</p>